config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount PaymentAPI::Base => "/"

  root "homepage#index"

  devise_for :admins
  devise_scope :admin do
    get "/admins/sign_out" => "devise/sessions#destroy"
  end

  devise_for :merchant_admins, class_name: "Merchant"
  devise_scope :merchant_admin do
    get "/merchant_admins/sign_out" => "devise/sessions#destroy"
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/*path" => "homepage#index", constraints: lambda { |request|
    !request.xhr? && request.format.html? &&
      !(request.path.start_with?("/admins") || request.path.start_with?("/merchant_admins"))
  }
end

app/controllers/homepage_controller.rb
# frozen_string_literal: true

class HomepageController < ApplicationController
  def index
  end
end

app/views/homepage/index.html.slim
nav.p-2[style="text-align: right"]
  - if admin_signed_in?
    = link_to(destroy_admin_session_path, method: :delete) do
      button.btn.btn-dark.m-1[type="button"]
        | Logout as Admin
  - elsif merchant_admin_signed_in?
    = link_to(destroy_merchant_admin_session_path, method: :delete) do
      button.btn.btn-dark.m-1[type="button"]
        | Logout as Merchant
  - else
    = link_to(new_admin_session_path) do
      button.btn.btn-dark.m-1[type="button"]
        | Login as Admin
    = link_to(new_merchant_admin_session_path) do
      button.btn.btn-dark.m-1[type="button"]
        | Login as Merchant